### ISSUE TITLE
pywin32 dependency

### ISSUE THREAD

**Issue by sbesson** [conda-forge/omero-py-feedstock#4]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Trying to test the installation of `omero-py` using this new feedstock and https://github.com/conda-forge/zeroc-ice-feedstock/pull/21 on a M1 

```
(base) sbesson@Sebastiens-MacBook-Pro ~ % cat environment.yml 
---
name: omero_py
channels:
  - conda-forge
  - defaults
dependencies:
  - omero-py
(base) sbesson@Sebastiens-MacBook-Pro ~ % conda env create -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                       
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                       

UnsatisfiableError: The following specifications were found to be incompatible with your system:

  - feature:/osx-arm64::__unix==0=0
  - omero-py -> pywin32-on-windows -> __unix

Your installed version is: 0
```

This had already been flagged in https://github.com/ome/conda-omero-py/issues/13 and and fixed in the package  shipped in the `ome` conda channel by removing the `noarch` - see https://github.com/ome/conda-omero-py/pull/1

### Installed packages

```shell
(base) sbesson@Sebastiens-MacBook-Pro ~ % conda list
# packages in environment at /Users/sbesson/miniconda3:
#
# Name                    Version                   Build  Channel
brotlipy                  0.7.0           py38h1a28f6b_1002  
ca-certificates           2021.10.26           hca03da5_2  
certifi                   2021.10.8        py38hca03da5_2  
cffi                      1.15.0           py38h22df2f2_1  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
conda                     4.11.0           py38hca03da5_0  
conda-package-handling    1.7.3            py38h1a28f6b_1  
cryptography              36.0.0           py38h834c97f_0  
idna                      3.3                pyhd3eb1b0_0  
libcxx                    12.0.0               hf6beb65_1  
libffi                    3.4.2                hc377ac9_2  
ncurses                   6.3                  h1a28f6b_2  
openssl                   1.1.1m               h1a28f6b_0  
pip                       21.2.4           py38hca03da5_0  
pycosat                   0.6.3            py38h1a28f6b_0  
pycparser                 2.21               pyhd3eb1b0_0  
pyopenssl                 22.0.0             pyhd3eb1b0_0  
pysocks                   1.7.1            py38hca03da5_0  
python                    3.8.11          h35b60ff_4_cpython  
python.app                3                py38h1230e6a_0  
readline                  8.1.2                h1a28f6b_1  
requests                  2.27.1             pyhd3eb1b0_0  
ruamel_yaml               0.15.100         py38h1a28f6b_0  
setuptools                58.0.4           py38hca03da5_1  
six                       1.16.0             pyhd3eb1b0_1  
sqlite                    3.37.2               h1058600_0  
tk                        8.6.11               hb8d0fd4_0  
tqdm                      4.62.3             pyhd3eb1b0_1  
urllib3                   1.26.8             pyhd3eb1b0_0  
wheel                     0.37.1             pyhd3eb1b0_0  
xz                        5.2.5                h1a28f6b_0  
yaml                      0.2.5                h1a28f6b_0  
zlib                      1.2.11               h5a0b063_4
```

### Environment info

```shell
(base) sbesson@Sebastiens-MacBook-Pro ~ % conda info

     active environment : base
    active env location : /Users/sbesson/miniconda3
            shell level : 1
       user config file : /Users/sbesson/.condarc
 populated config files : 
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.8.11.final.0
       virtual packages : __osx=12.3.1=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /Users/sbesson/miniconda3  (writable)
      conda av data dir : /Users/sbesson/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/sbesson/miniconda3/pkgs
                          /Users/sbesson/.conda/pkgs
       envs directories : /Users/sbesson/miniconda3/envs
                          /Users/sbesson/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.11.0 requests/2.27.1 CPython/3.8.11 Darwin/21.4.0 OSX/12.3.1
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by manics** [comment]
@bollwyvl https://github.com/conda-forge/pywin32-on-windows-feedstock is noarch, but does it need some more magic to work with osx-arm64?

**Comment by bollwyvl** [comment]
I don't have a way to test that natively, but on a linux box, with this:

```bash
CONDA_SUBDIR=osx-arm64 conda create -c conda-forge -c nodefaults -n foo --dry-run omero-py
```

i get:

<details>
<pre>
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: ~/mc3/envs/foo

  added / updated specs:
    - omero-py


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    appdirs-1.4.4              |     pyh9f0ad1d_0          13 KB
    brotlipy-0.7.0             |py39hb18efdd_1004         341 KB
    bzip2-1.0.8                |       h3422bc3_4         148 KB
    ca-certificates-2021.10.8  |       h4653dfc_0         139 KB
    certifi-2021.10.8          |   py39h2804cbe_2         145 KB
    cffi-1.15.0                |   py39h52b1de0_0         219 KB
    cryptography-36.0.2        |   py39hbe5e4b8_1         1.3 MB
    freetype-2.10.4            |       h17b34a0_1         874 KB
    future-0.18.2              |   py39h2804cbe_5         714 KB
    giflib-5.2.1               |       h27ca646_2          72 KB
    jbig-2.1                   |    h3422bc3_2003          42 KB
    jpeg-9e                    |       h3422bc3_0         257 KB
    lcms2-2.12                 |       had6a04f_0         369 KB
    lerc-3.0                   |       hbdafb3b_0         145 KB
    libblas-3.9.0              |13_osxarm64_openblas          12 KB
    libcblas-3.9.0             |13_osxarm64_openblas          12 KB
    libcxx-13.0.1              |       h6a5c8ee_0         1.1 MB
    libdeflate-1.10            |       h3422bc3_0          56 KB
    libffi-3.4.2               |       h3422bc3_5          38 KB
    libgfortran-5.0.0.dev0     |11_0_1_hf114ba7_23          19 KB
    libgfortran5-11.0.1.dev0   |      hf114ba7_23         901 KB
    libiconv-1.16              |       h642e427_0         1.3 MB
    liblapack-3.9.0            |13_osxarm64_openblas          12 KB
    libopenblas-0.3.18         |openmp_h5dd58f0_0         3.9 MB
    libpng-1.6.37              |       hf7e6567_2         293 KB
    libtiff-4.3.0              |       h77dc3b6_3         595 KB
    libwebp-1.2.2              |       h0d20362_0          79 KB
    libwebp-base-1.2.2         |       h3422bc3_1         600 KB
    libxcb-1.13                |    h9b22ae9_1004         345 KB
    libzlib-1.2.11             |    h90dfc92_1014          55 KB
    llvm-openmp-13.0.1         |       h455960f_1         276 KB
    lz4-c-1.9.3                |       hbdafb3b_1         147 KB
    ncurses-6.3                |       hc470f4d_0         919 KB
    numpy-1.22.3               |   py39h690d673_1         5.7 MB
    omero-py-5.11.1            |     pyhd8ed1ab_0         1.8 MB
    openjpeg-2.4.0             |       h062765e_1         422 KB
    openssl-1.1.1n             |       h90dfc92_0         1.7 MB
    pillow-9.1.0               |   py39hd72dd6b_0        45.2 MB
    pthread-stubs-0.4          |    h27ca646_1001           6 KB
    pysocks-1.7.1              |   py39h2804cbe_5          28 KB
    python-3.9.12              |hfc7342c_1_cpython        12.3 MB
    python_abi-3.9             |           2_cp39           4 KB
    pywin32-on-windows-0.1.0   |     pyh1179c8e_3           5 KB
    pyyaml-6.0                 |   py39hb18efdd_4         166 KB
    readline-8.1               |       hedafd6a_0         259 KB
    setuptools-62.0.0          |   py39h2804cbe_0         1.3 MB
    sqlite-3.37.1              |       h7e3ccbd_0         1.6 MB
    tk-8.6.12                  |       he1e0b03_0         3.2 MB
    xorg-libxau-1.0.9          |       h27ca646_0          12 KB
    xorg-libxdmcp-1.1.3        |       h27ca646_0          18 KB
    xz-5.2.5                   |       h642e427_1         222 KB
    yaml-0.2.5                 |       h3422bc3_2          86 KB
    zeroc-ice-3.6.5            |   py39h6e8f42b_3         2.3 MB
    zlib-1.2.11                |    h90dfc92_1014          85 KB
    zstd-1.5.2                 |       h861e0a7_0         369 KB
    ------------------------------------------------------------
                                           Total:        92.0 MB

The following NEW packages will be INSTALLED:

  appdirs            conda-forge/noarch::appdirs-1.4.4-pyh9f0ad1d_0
  brotlipy           conda-forge/osx-arm64::brotlipy-0.7.0-py39hb18efdd_1004
  bzip2              conda-forge/osx-arm64::bzip2-1.0.8-h3422bc3_4
  ca-certificates    conda-forge/osx-arm64::ca-certificates-2021.10.8-h4653dfc_0
  certifi            conda-forge/osx-arm64::certifi-2021.10.8-py39h2804cbe_2
  cffi               conda-forge/osx-arm64::cffi-1.15.0-py39h52b1de0_0
  charset-normalizer conda-forge/noarch::charset-normalizer-2.0.12-pyhd8ed1ab_0
  cryptography       conda-forge/osx-arm64::cryptography-36.0.2-py39hbe5e4b8_1
  freetype           conda-forge/osx-arm64::freetype-2.10.4-h17b34a0_1
  future             conda-forge/osx-arm64::future-0.18.2-py39h2804cbe_5
  giflib             conda-forge/osx-arm64::giflib-5.2.1-h27ca646_2
  idna               conda-forge/noarch::idna-3.3-pyhd8ed1ab_0
  jbig               conda-forge/osx-arm64::jbig-2.1-h3422bc3_2003
  jpeg               conda-forge/osx-arm64::jpeg-9e-h3422bc3_0
  lcms2              conda-forge/osx-arm64::lcms2-2.12-had6a04f_0
  lerc               conda-forge/osx-arm64::lerc-3.0-hbdafb3b_0
  libblas            conda-forge/osx-arm64::libblas-3.9.0-13_osxarm64_openblas
  libcblas           conda-forge/osx-arm64::libcblas-3.9.0-13_osxarm64_openblas
  libcxx             conda-forge/osx-arm64::libcxx-13.0.1-h6a5c8ee_0
  libdeflate         conda-forge/osx-arm64::libdeflate-1.10-h3422bc3_0
  libffi             conda-forge/osx-arm64::libffi-3.4.2-h3422bc3_5
  libgfortran        conda-forge/osx-arm64::libgfortran-5.0.0.dev0-11_0_1_hf114ba7_23
  libgfortran5       conda-forge/osx-arm64::libgfortran5-11.0.1.dev0-hf114ba7_23
  libiconv           conda-forge/osx-arm64::libiconv-1.16-h642e427_0
  liblapack          conda-forge/osx-arm64::liblapack-3.9.0-13_osxarm64_openblas
  libopenblas        conda-forge/osx-arm64::libopenblas-0.3.18-openmp_h5dd58f0_0
  libpng             conda-forge/osx-arm64::libpng-1.6.37-hf7e6567_2
  libtiff            conda-forge/osx-arm64::libtiff-4.3.0-h77dc3b6_3
  libwebp            conda-forge/osx-arm64::libwebp-1.2.2-h0d20362_0
  libwebp-base       conda-forge/osx-arm64::libwebp-base-1.2.2-h3422bc3_1
  libxcb             conda-forge/osx-arm64::libxcb-1.13-h9b22ae9_1004
  libzlib            conda-forge/osx-arm64::libzlib-1.2.11-h90dfc92_1014
  llvm-openmp        conda-forge/osx-arm64::llvm-openmp-13.0.1-h455960f_1
  lz4-c              conda-forge/osx-arm64::lz4-c-1.9.3-hbdafb3b_1
  ncurses            conda-forge/osx-arm64::ncurses-6.3-hc470f4d_0
  numpy              conda-forge/osx-arm64::numpy-1.22.3-py39h690d673_1
  omero-py           conda-forge/noarch::omero-py-5.11.1-pyhd8ed1ab_0
  openjpeg           conda-forge/osx-arm64::openjpeg-2.4.0-h062765e_1
  openssl            conda-forge/osx-arm64::openssl-1.1.1n-h90dfc92_0
  pillow             conda-forge/osx-arm64::pillow-9.1.0-py39hd72dd6b_0
  pip                conda-forge/noarch::pip-22.0.4-pyhd8ed1ab_0
  pthread-stubs      conda-forge/osx-arm64::pthread-stubs-0.4-h27ca646_1001
  pycparser          conda-forge/noarch::pycparser-2.21-pyhd8ed1ab_0
  pyopenssl          conda-forge/noarch::pyopenssl-22.0.0-pyhd8ed1ab_0
  pysocks            conda-forge/osx-arm64::pysocks-1.7.1-py39h2804cbe_5
  python             conda-forge/osx-arm64::python-3.9.12-hfc7342c_1_cpython
  python_abi         conda-forge/osx-arm64::python_abi-3.9-2_cp39
  pywin32-on-windows conda-forge/noarch::pywin32-on-windows-0.1.0-pyh1179c8e_3
  pyyaml             conda-forge/osx-arm64::pyyaml-6.0-py39hb18efdd_4
  readline           conda-forge/osx-arm64::readline-8.1-hedafd6a_0
  requests           conda-forge/noarch::requests-2.27.1-pyhd8ed1ab_0
  setuptools         conda-forge/osx-arm64::setuptools-62.0.0-py39h2804cbe_0
  sqlite             conda-forge/osx-arm64::sqlite-3.37.1-h7e3ccbd_0
  tk                 conda-forge/osx-arm64::tk-8.6.12-he1e0b03_0
  tzdata             conda-forge/noarch::tzdata-2022a-h191b570_0
  urllib3            conda-forge/noarch::urllib3-1.26.9-pyhd8ed1ab_0
  wheel              conda-forge/noarch::wheel-0.37.1-pyhd8ed1ab_0
  xorg-libxau        conda-forge/osx-arm64::xorg-libxau-1.0.9-h27ca646_0
  xorg-libxdmcp      conda-forge/osx-arm64::xorg-libxdmcp-1.1.3-h27ca646_0
  xz                 conda-forge/osx-arm64::xz-5.2.5-h642e427_1
  yaml               conda-forge/osx-arm64::yaml-0.2.5-h3422bc3_2
  zeroc-ice          conda-forge/osx-arm64::zeroc-ice-3.6.5-py39h6e8f42b_3
  zlib               conda-forge/osx-arm64::zlib-1.2.11-h90dfc92_1014
  zstd               conda-forge/osx-arm64::zstd-1.5.2-h861e0a7_0
</pre>
</details>

with a local of:

<details>
<pre>
conda info

     active environment : base
    active env location : ~/mc3
            shell level : 1
       user config file : ~/.condarc
 populated config files : ~/.condarc
          conda version : 4.12.0
    conda-build version : 3.21.8
         python version : 3.9.10.final.0
       virtual packages : __cuda=11.4=0
                          __linux=5.4.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : ~/mc3  (writable)
      conda av data dir : ~/mc3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : ~/mc3/pkgs
                          ~/.conda/pkgs
       envs directories : ~/mc3/envs
                          ~/.conda/envs
               platform : linux-64
             user-agent : conda/4.12.0 requests/2.25.1 CPython/3.9.10 Linux/5.4.0-105-generic ubuntu/20.04.4 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
</pre>
</details>

so maybe:
- try without `defaults`
- try updating `conda`
  - maybe with the new solver?
- try `mamba`
- try solving first with `conda-lock --kind explicit` and creating from that

But if none of that works, accept having to drop `noarch: python` and add the platform-specific dependencies

**Comment by sbesson** [comment]
Thanks @bollwyvl, dropping `defaults` from `environment.yml` was sufficient to get the package installed. Now running into a separate runtime error but this can be safely closed

**Comment by bollwyvl** [comment]
> sufficient to get the package installed.

:tada: 

> separate runtime error but this can be safely closed

If it's related to `pywin32-on-windows`, please share!

**Comment by sbesson** [comment]
> If it's related to pywin32-on-windows, please share!

No nothing related to `pywin32`. I am getting the same issue as https://github.com/conda-forge/zeroc-ice-feedstock/pull/21#issuecomment-1087946339 i.e. this is an issue to the `zeroc-ice` recipe
